const plans=[
{d:"Lun",t:"Lower + core",mins:"50–60",home:[["Goblet squat","3×8–12"],["DB Romanian deadlift","3×8–10"],["Bulgarian split squat","3×8/side"],["Calf raise","3×12–15"],["Dead bug","3×8/side"]],gym:[["Leg press / squat","3×8–12"],["Romanian deadlift","3×8–10"],["Bulgarian split squat","3×8/side"],["Calf raise","3×12–15"],["Back extension","3×10–15"]]},
{d:"Mar",t:"Z2",mins:"30–40",cardio:true},{d:"Gio",t:"Upper",mins:"45–55",home:[["Pull-up","4×5–8"],["Dip","3×8–12"],["DB press","3×8–12"],["DB row","3×8–12"],["Lateral raise","3×12–15"]],gym:[["Pull-up / lat machine","4×5–8"],["Dip / chest press","3×8–12"],["DB bench","3×8–12"],["Cable row","3×8–12"],["Lateral raise","3×12–15"]]},
{d:"Sab",t:"Lower posterior",mins:"50–60",home:[["Goblet squat","3×8–12"],["DB hip thrust","3×10–15"],["Reverse lunge","3×8/side"],["Single-leg RDL","3×8/side"],["Side plank","3×30–45s"]],gym:[["Squat","3×6–10"],["Hip thrust","3×8–12"],["Reverse lunge","3×8/side"],["Leg curl","3×10–15"],["Back extension","3×10–15"]]},
{d:"Dom",t:"Z2 easy",mins:"35–50",cardio:true}];
let state=JSON.parse(localStorage.getItem("sc-state")||'{"place":"CASA","history":[]}');let selected=0;const app=document.querySelector("#app");const save=()=>localStorage.setItem("sc-state",JSON.stringify(state));
function home(){let p=plans[selected];app.innerHTML=`<section class="card"><div class="row"><div><small>${p.d}</small><h2>${p.t}</h2></div><span class="pill">${p.mins} min</span></div>${p.cardio?cardio(p):strength(p)}<div class="actions">${p.cardio?"":'<button class="secondary" onclick="togglePlace()">📍 '+state.place+'</button>'}<button onclick="finish()">Salva sessione</button></div></section>`;document.querySelector("#title").textContent="Oggi";}
function strength(p){return `<div id="ex">${p[state.place==="CASA"?"home":"gym"].map((e,i)=>`<div class="exercise"><b>${e[0]}</b><div class="muted">${e[1]} · RPE target 7–8</div><div class="set"><label>KG<input type="number" inputmode="decimal" data-i="${i}" data-k="kg"></label><label>REPS<input type="number" inputmode="numeric" data-i="${i}" data-k="reps"></label><label>RPE<input type="number" inputmode="decimal" min="1" max="10" data-i="${i}" data-k="rpe"></label></div></div>`).join("")}</div>`}
function cardio(){return `<div class="exercise"><b>Corsa o cyclette</b><p class="muted">Z2: ritmo sostenibile e conversazionale. Parti conservativo.</p><div class="set"><label>MIN<input id="minutes" type="number" value="35"></label><label>KM<input id="km" type="number" inputmode="decimal"></label><label>RPE<input id="crpe" type="number" value="3"></label></div></div>`}
function togglePlace(){state.place=state.place==="CASA"?"PALESTRA":"CASA";save();home()}
function finish(){let p=plans[selected],entry={date:new Date().toISOString(),name:p.t,place:state.place};if(p.cardio){entry.minutes=+document.querySelector("#minutes").value;entry.km=+document.querySelector("#km").value;entry.rpe=+document.querySelector("#crpe").value}else{entry.sets=[...document.querySelectorAll(".set input")].reduce((a,x)=>{let i=x.dataset.i;a[i]=a[i]||{};a[i][x.dataset.k]=+x.value;return a},[])}state.history.unshift(entry);save();alert("Allenamento salvato ✓");historyView()}
function plan(){document.querySelector("#title").textContent="Piano";app.innerHTML=`<div class="grid">${plans.map((p,i)=>`<div class="day" onclick="selected=${i};setTab('home');home()"><small>${p.d}</small><h3>${p.t}</h3><p class="muted">${p.mins} min</p></div>`).join("")}</div><section class="card"><b>Regola di progressione</b><p class="muted">Quando completi il range alto con RPE ≤8, aumenta leggermente il carico la seduta successiva. Prime 2 settimane: evita il cedimento.</p></section>`}
function historyView(){document.querySelector("#title").textContent="Storico";app.innerHTML=state.history.length?state.history.map((h,i)=>`<div class="card"><div class="row"><div><small>${new Date(h.date).toLocaleDateString("it-IT")}</small><h3>${h.name}</h3><span class="muted">${h.place||"CARDIO"}${h.minutes?" · "+h.minutes+" min":""}</span></div><button class="danger" style="width:auto" onclick="del(${i})">×</button></div></div>`).join(""):'<div class="card"><p class="muted">Nessun allenamento registrato. Il primo comparirà qui.</p></div>'}
function del(i){state.history.splice(i,1);save();historyView()}function setTab(t){document.querySelectorAll("nav button").forEach(b=>b.classList.toggle("active",b.dataset.tab===t))}
document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>{setTab(b.dataset.tab);b.dataset.tab==="home"?home():b.dataset.tab==="plan"?plan():historyView()});home();