'use strict';
function v3FmtMins(mins){if(mins==null)return '–';const m=Math.round(mins);return m>=60?Math.floor(m/60)+'h '+String(m%60).padStart(2,'0')+'m':m+' min'}
function v3ActivityMeta(a){const bits=[];if(a.distanceKm!=null)bits.push(a.distanceKm.toFixed(2)+' km');if(a.minutes!=null)bits.push(v3FmtMins(a.minutes));if(a.avgHr!=null)bits.push('FC '+Math.round(a.avgHr));if(a.trainingLoad!=null)bits.push('Load '+a.trainingLoad);return bits.join(' · ')}
function v3ActivityLine(a){return `<div class="history-item"><div class="row start"><div class="grow"><b>${esc(a.name)}</b><div class="muted tiny">${fmtDate(a.date,{day:'numeric',month:'short'})} · ${esc(a.source||'')}</div></div><span class="pill">${esc(v3ActivityMeta(a)||a.kind)}</span></div></div>`}
function v3Metric(label,value,source,onclick=''){return `<button class="metric metric-btn v3metric" ${onclick?`onclick="${onclick}"`:''}><small>${esc(label)}</small><b>${value}</b>${source?`<em>${esc(source)}</em>`:''}</button>`}
function v3ReasonRows(parts){if(!parts.length)return '<p class="muted small">Mancano ancora dati fisiologici sufficienti.</p>';return parts.slice(0,5).map(x=>`<div class="reason-row"><div><b>${esc(x.label)}</b><small>${esc(x.note||'')} · ${esc(x.source||'')}</small></div><span>${Math.round(x.value)}</span></div>`).join('')}

todayView=function(date=state.selectedDate||v3Today()){
  state.selectedDate=date;save();setTab('today');
  const rec=recommendation(date),rd=v3Readiness(date),h=rd.health,acts=historyOn(date),band=readinessBand(rec.score);
  setHeader(date===v3Today()?'Oggi':fmtDate(date,{weekday:'long',day:'numeric',month:'long'}),'');
  const shift=rd.shift?`<span class="pill warn">${esc(rd.shift.title)}</span>`:'',nap=h.nap&&h.nap>.15?` · +${h.nap.toFixed(1)} h nap`:'';
  const ratio=v3Num(state.coros.loadRatio),short=v3Num(state.coros.shortLoad),long=v3Num(state.coros.longLoad);
  app.innerHTML=`<div class="stack v3stack">
  <section class="card hero v3hero"><div class="row start"><div class="grow"><div class="pills"><span class="pill ${band}">${readinessLabel(rec.score)}</span>${shift}</div><h2 style="margin-top:12px">${esc(rec.session.title)}</h2><p class="muted small">${esc(rec.reason)} · ${esc(rec.session.focus||'')}</p></div><div class="score-ring" style="--score:${rec.score}"><b>${rec.score}</b><small>READY</small></div></div><div class="actions"><button class="btn" onclick="startRecommended('${date}')">${rec.session.type==='recovery'?'Apri':'Inizia'}</button><button class="btn secondary" onclick="openCheckin('${date}')">Come mi sento</button></div></section>
  <section class="grid2 v3health">${v3Metric('Sonno principale',h.mainSleep!=null?h.mainSleep.toFixed(2)+' h'+nap:'–',h.sleepSource,`healthTrendPage('sleep')`)}${v3Metric('HRV sonno',h.hrv!=null?Math.round(h.hrv*10)/10+' ms':'–',h.hrvSource,`healthTrendPage('hrv')`)}${v3Metric('FC riposo',h.rhr!=null?Math.round(h.rhr)+' bpm':'–',h.rhrSource,`healthTrendPage('rhr')`)}${v3Metric('Passi',h.steps!=null?Math.round(h.steps).toLocaleString('it-IT'):'–',h.stepsSource,`healthTrendPage('steps')`)}</section>
  <section class="card"><div class="row"><div><h3>Perché oggi</h3><p class="muted tiny" style="margin:0">Il punteggio cambia solo quando cambiano i dati sottostanti.</p></div><span class="pill">${rec.adjust}</span></div><div style="margin-top:10px">${v3ReasonRows(rd.parts)}</div></section>
  <section class="card"><div class="row"><h3>Carico COROS</h3><span class="pill">${state.coros.synced||state.coros.syncedAt?.slice(0,10)||'–'}</span></div><div class="grid3" style="margin-top:10px"><div class="metric"><small>Breve</small><b>${short??'–'}</b></div><div class="metric"><small>Lungo</small><b>${long??'–'}</b></div><div class="metric"><small>Ratio</small><b>${ratio!=null?ratio.toFixed(2):'–'}</b></div></div></section>
  ${acts.length?`<section class="card"><div class="row"><h3>Registrato oggi</h3><span class="pill good">${acts.length}</span></div>${acts.map(v3ActivityLine).join('')}</section>`:''}
  <section class="card soft"><div class="row"><div><h3>Ultime attività</h3><p class="muted tiny" style="margin:0">COROS + SmartCoach</p></div><button class="swap" onclick="trendView()">Vedi trend</button></div>${unifiedActivities().slice(0,3).map(v3ActivityLine).join('')||'<p class="muted small">Nessuna attività sincronizzata.</p>'}</section></div>`;
};

weekView=function(){
  setTab('week');setHeader('Settimana','piano adattivo + attività reali');
  const {days,plan}=v3PlanWeek(state.selectedDate||v3Today()),today=v3Today();
  const rows=days.map(d=>{const p=plan[d],acts=p.actual||[],actual=acts.length?acts.map(a=>a.name).join(' + '):null,s=p.session,main=actual||s?.short||'Recupero',sub=[];
    if(actual)sub.push('registrato · '+[...new Set(acts.map(a=>a.source))].join('/'));else if(s)sub.push('proposto');if(p.shift)sub.push(p.shift.title);
    return `<button class="day ${d===today?'today':''} ${acts.length?'done':''}" onclick="todayView('${d}')"><div><div class="dow">${parseDate(d).toLocaleDateString('it-IT',{weekday:'short'})}</div><div class="date">${parseDate(d).getDate()}</div></div><div><b>${esc(main)}</b><div class="muted tiny">${sub.map(x=>p.shift&&x===p.shift.title?`<span class="shift">${esc(x)}</span>`:esc(x)).join(' · ')}</div></div><i class="status-dot"></i></button>`}).join('');
  app.innerHTML=`<div class="stack"><section class="card"><div class="notice goodbox">Il piano non è legato ai giorni fissi: attività registrate, recupero e turni spostano automaticamente ciò che resta da fare.</div><div class="week" style="margin-top:12px">${rows}</div></section></div>`;
};

trainingHub=function(){
  setTab('train');setHeader('Training','scegli o segui il piano');const d=v3Today(),rec=recommendation(d),z=state.coros.hrZones||{},run=unifiedActivities().find(a=>a.kind==='run');
  const adaptive=s=>{const raw=typeof s.mins==='number'?s.mins:(s.type==='cardio'?35:50),av=rec.availableMinutes||raw,f=s.type==='cardio'?rec.cardioFactor:(rec.setDelta<=-2?.6:rec.setDelta<0?.8:1);return Math.max(15,Math.round(Math.min(raw,av)*f))};
  const zones=(z.zones||[]).map(x=>`<div class="zone-row"><span>${esc(x.name)}</span><b>${esc(x.range)} bpm</b></div>`).join('');
  app.innerHTML=`<div class="stack v3stack"><section class="card hero"><div class="row"><div><span class="pill good">Consigliato oggi</span><h2 style="margin-top:10px">${esc(rec.session.title)}</h2><p class="muted small">${esc(rec.reason)}</p></div><div class="big">${adaptive(rec.session)}<small class="muted tiny"> min</small></div></div><button class="btn" style="margin-top:12px" onclick="startRecommended('${d}')">Apri allenamento</button></section>
  <section class="card"><div class="segment"><button class="${state.place==='CASA'?'active':''}" onclick="setPlace('CASA')">Casa</button><button class="${state.place==='PALESTRA'?'active':''}" onclick="setPlace('PALESTRA')">Palestra</button></div></section>
  <section class="card"><div class="row"><div><h3>Corsa / cardio</h3><p class="muted tiny" style="margin:0">Zone ufficiali COROS · soglia ${z.thresholdHr??'–'} bpm</p></div><span class="pill">${state.coros.thresholdPace||state.coros.fitness?.thresholdPace||'–'}</span></div><div class="grid2" style="margin-top:12px"><button class="menu" onclick="openSession('z2short','${d}')"><b>Z2 base</b><span>${adaptive(CARDIO.z2short)} min · ${(z.zones||[])[1]?.range||'–'} bpm</span></button><button class="menu" onclick="openSession('z2long','${d}')"><b>Z2 endurance</b><span>${adaptive(CARDIO.z2long)} min</span></button></div>${zones?`<div class="zones-compact">${zones}</div>`:''}${run?`<p class="muted tiny">Ultima corsa: ${esc(v3ActivityMeta(run))}</p>`:''}</section>
  <section class="card"><h3>Forza</h3><div class="menu-grid" style="margin-top:10px">${Object.values(STRENGTH).map(s=>`<button class="menu" onclick="openSession('${s.id}','${d}')"><b>${esc(s.short)}</b><span>${adaptive(s)} min · ${state.place==='CASA'?'casa':'palestra'}</span></button>`).join('')}</div></section></div>`;
};
setPlace=function(p){state.place=p;save();trainingHub()};

function v3RangeDays(){return +state.ui.trendRange||28}
function setTrendRange(n){state.ui.trendRange=n;save();trendView()}
function v3Within(a,days){const start=dateKey(addDays(TODAY(),-(days-1))),end=v3Today();return a.date>=start&&a.date<=end}
function v3WeeklyRunKm(days){const start=addDays(TODAY(),-(days-1)),ws=v3WeekStart(start),weeks=[];for(let d=new Date(ws);d<=TODAY();d=addDays(d,7)){const a=dateKey(d),b=dateKey(addDays(d,6)),km=v3Sum(unifiedActivities().filter(x=>x.kind==='run'&&x.date>=a&&x.date<=b).map(x=>x.distanceKm||0));weeks.push({date:a,value:Math.round(km*100)/100})}return weeks}
function v3LoadSeries(days){const start=dateKey(addDays(TODAY(),-(days-1)));return (state.coros.loadHistory||[]).filter(x=>x.date>=start).map(x=>({date:x.date,value:+x.ratio||0}))}
trendView=function(){
  setTab('trend');setHeader('Trend','dati reali, non baseline statiche');const days=v3RangeDays(),acts=unifiedActivities().filter(a=>v3Within(a,days)),runs=acts.filter(a=>a.kind==='run');
  const km=v3Sum(runs.map(a=>a.distanceKm||0)),active=v3Sum(acts.map(a=>a.minutes||0)),steps=v3Series('steps',days),sleep=v3Series('sleep',days),hrv=v3Series('hrv',days),rhr=v3Series('rhr',days),load=v3LoadSeries(days),runWeeks=v3WeeklyRunKm(days);
  const stepAvg=steps.length?Math.round(v3Sum(steps.map(x=>x.value))/steps.length):null,fitness=state.coros.fitness||state.coros,pred=state.coros.racePredictions||fitness.racePredictions||{};
  const chart=(title,rows,unit='')=>`<section class="card"><div class="row"><h3>${esc(title)}</h3><span class="pill">${rows.length} gg</span></div>${rows.length>1?sparkline(rows.map(x=>+x.value)):'<p class="muted small">Servono più dati sincronizzati.</p>'}${rows.length?`<div class="row tiny muted"><span>${fmtDate(rows[0].date)}</span><span>${Math.round(rows.at(-1).value*100)/100} ${esc(unit)}</span></div>`:''}</section>`;
  app.innerHTML=`<div class="stack v3stack"><section class="card"><div class="segment"><button class="${days===7?'active':''}" onclick="setTrendRange(7)">7g</button><button class="${days===28?'active':''}" onclick="setTrendRange(28)">28g</button><button class="${days===90?'active':''}" onclick="setTrendRange(90)">90g</button></div></section>
  <section class="grid2"><div class="metric"><small>Sessioni · ${days}g</small><b>${acts.length}</b></div><div class="metric"><small>Corsa · ${days}g</small><b>${km.toFixed(1)} km</b></div><div class="metric"><small>Tempo attivo</small><b>${Math.round(active)} min</b></div><div class="metric"><small>Passi medi/g</small><b>${stepAvg!=null?stepAvg.toLocaleString('it-IT'):'–'}</b></div></section>
  <section class="card"><div class="row"><h3>Running Fitness · COROS</h3><span class="pill good">live</span></div><div class="grid2" style="margin-top:10px"><div class="metric"><small>Running Level</small><b>${fitness.runningLevel??'–'}</b></div><div class="metric"><small>VO₂max</small><b>${fitness.vo2max??'–'}</b></div><div class="metric"><small>5 km</small><b>${pred.k5||'–'}</b></div><div class="metric"><small>10 km</small><b>${pred.k10||'–'}</b></div></div></section>
  ${chart('Km corsa · per settimana',runWeeks,'km')}${chart('Passi · giornalieri',steps,'')}${chart('Sonno principale',sleep,'h')}${chart('HRV sonno',hrv,'ms')}${chart('FC riposo',rhr,'bpm')}${chart('Load ratio COROS',load,'')}
  <section class="card"><div class="row"><h3>Storico unificato</h3><span class="pill">${unifiedActivities().length}</span></div>${unifiedActivities().slice(0,40).map(v3ActivityLine).join('')||'<p class="muted">Nessuna attività sincronizzata.</p>'}</section></div>`;
};

healthTrendPage=function(kind){
  const meta={sleep:['Sonno principale','h'],hrv:['HRV sonno','ms'],rhr:['FC a riposo','bpm'],steps:['Passi','']},m=meta[kind]||meta.hrv,rows=v3Series(kind,90);
  setHeader(m[0],'ultimi 90 giorni');setTab('today');app.innerHTML=`<div class="stack"><button class="btn ghost smallbtn" onclick="todayView()">‹ Oggi</button><section class="card"><div class="row"><h2>${m[0]}</h2><span class="pill">${rows.length} gg</span></div>${rows.length>1?sparkline(rows.map(x=>x.value)):'<p class="muted small">Dati insufficienti.</p>'}${rows.slice(-30).reverse().map(x=>`<div class="history-item row"><span>${fmtDate(x.date,{day:'numeric',month:'short'})}</span><b>${Math.round(x.value*100)/100} ${m[1]}</b></div>`).join('')}</section>${kind==='sleep'?'<section class="card"><p class="muted small">Il valore principale è la notte; i pisolini restano separati e non gonfiano il sonno notturno.</p></section>':''}</div>`;
};
openCheckin=function(date=state.selectedDate||v3Today()){
  const r=state.readiness?.[date]||{},h=v3HealthDay(date);setHeader('Come mi sento',fmtDate(date,{weekday:'long',day:'numeric',month:'long'}));
  app.innerHTML=`<div class="stack"><section class="card"><div class="notice goodbox">Sonno, HRV, FC riposo e COROS Recovery arrivano automaticamente. Qui inserisci solo ciò che il sensore non può sapere.</div><div class="form-grid" style="margin-top:14px"><label>Energia<select id="ciEnergy">${opts5(r.energy||3)}</select></label><label>Dolori muscolari<select id="ciSore">${opts5(r.soreness||2)}</select></label><label>Stress<select id="ciStress">${opts5(r.stress||3)}</select></label><label>Tempo disponibile<select id="ciTime"><option value="20" ${+r.availableMinutes===20?'selected':''}>20 min</option><option value="35" ${+r.availableMinutes===35?'selected':''}>35 min</option><option value="50" ${!r.availableMinutes||+r.availableMinutes===50?'selected':''}>50 min</option><option value="60" ${+r.availableMinutes===60?'selected':''}>60+ min</option></select></label></div><div class="grid3" style="margin-top:12px"><div class="metric"><small>Sonno auto</small><b>${h.mainSleep!=null?h.mainSleep.toFixed(1)+' h':'–'}</b></div><div class="metric"><small>HRV auto</small><b>${h.hrv!=null?Math.round(h.hrv)+' ms':'–'}</b></div><div class="metric"><small>RHR auto</small><b>${h.rhr!=null?Math.round(h.rhr):'–'}</b></div></div><button class="btn" style="margin-top:14px" onclick="saveCheckinV3('${date}')">Salva</button></section></div>`;
};
function saveCheckinV3(date){state.readiness[date]={...(state.readiness[date]||{}),energy:+val('ciEnergy'),soreness:+val('ciSore'),stress:+val('ciStress'),availableMinutes:+val('ciTime')||50};save();toast('Check-in salvato');todayView(date)}


goalsPage=function(){
  const g=state.settings.goals||{},w=state.profile.weightKg||73,fit=state.coros.fitness||state.coros,pred=state.coros.racePredictions||fit.racePredictions||{};
  setHeader('Obiettivi','guidano il piano, non sono solo note');
  app.innerHTML=`<div class="stack"><button class="btn ghost smallbtn" onclick="backMore()">‹ Altro</button>
  <section class="card hero"><div class="grid2"><div class="metric"><small>Peso</small><b>${w} → ${g.weightKg||75} kg</b></div><div class="metric"><small>5 km target</small><b>${g.run5kMin||25} min</b></div><div class="metric"><small>5 km COROS</small><b>${pred.k5||'–'}</b></div><div class="metric"><small>Running Level</small><b>${fit.runningLevel??'–'}</b></div></div></section>
  <section class="card"><h3>Priorità del motore</h3><p class="muted small">Il planner usa questi obiettivi insieme a recupero, turni e attività già fatte. Target base attuale: 3 sedute forza + 2 sedute aerobiche, distribuite dinamicamente.</p></section>
  <section class="card"><h3>Modifica</h3><div class="form-grid"><label>Peso target kg<input id="goalWeight" type="number" step=".1" value="${g.weightKg||75}"></label><label>5 km target (min)<input id="goal5k" type="number" step=".5" value="${g.run5kMin||25}"></label><label>Obiettivo muscolare<select id="goalMuscle"><option value="hypertrophy" ${g.muscle==='hypertrophy'?'selected':''}>Ipertrofia</option><option value="strength" ${g.muscle==='strength'?'selected':''}>Forza</option><option value="maintenance" ${g.muscle==='maintenance'?'selected':''}>Mantenimento</option></select></label><label>Priorità<select id="goalPriority"><option value="legs-posterior-chain" ${g.priority==='legs-posterior-chain'?'selected':''}>Gambe + lower back</option><option value="balanced" ${g.priority==='balanced'?'selected':''}>Bilanciato</option><option value="upper" ${g.priority==='upper'?'selected':''}>Upper</option></select></label></div><button class="btn" style="margin-top:12px" onclick="saveGoals()">Aggiorna piano</button></section></div>`;
};
saveGoals=function(){
  state.settings.goals={...(state.settings.goals||{}),weightKg:+val('goalWeight')||75,run5kMin:+val('goal5k')||25,muscle:val('goalMuscle'),priority:val('goalPriority'),aerobic:'rebuild-z2'};
  const w=state.profile.weightKg||73,d=state.settings.goals.weightKg-w;
  state.settings.nutrition={...(state.settings.nutrition||{}),calories:Math.round(w*(d>1?34:d<-1?28:32)),protein:Math.round(w*2),fat:Math.round(w*.9)};
  const kcal=state.settings.nutrition.calories,p=state.settings.nutrition.protein,fat=state.settings.nutrition.fat;
  state.settings.nutrition.carbs=Math.max(100,Math.round((kcal-p*4-fat*9)/4));save();toast('Obiettivi aggiornati');goalsPage();
};

recoveryPage=function(){
  const d=state.selectedDate||v3Today(),rd=v3Readiness(d),rec=recommendation(d),loads=(state.coros.loadHistory||[]).slice(-14),manual=v3ManualShifts(),all=[...(state.calendar?.shifts||[]),...manual].sort((a,b)=>a.date.localeCompare(b.date));
  setHeader('Recovery','dati reali + turni');
  app.innerHTML=`<div class="stack"><button class="btn ghost smallbtn" onclick="backMore()">‹ Altro</button>
  <section class="card hero"><div class="row"><div><span class="pill ${readinessBand(rd.score)}">${readinessLabel(rd.score)}</span><h2 style="margin-top:10px">${rd.score}/100</h2><p class="muted small">${esc(rec.reason)}</p></div><div class="score-ring" style="--score:${rd.score}"><b>${rd.score}</b><small>READY</small></div></div><div style="margin-top:12px">${v3ReasonRows(rd.parts)}</div><button class="btn secondary" style="margin-top:12px" onclick="openCheckin('${d}')">Come mi sento</button></section>
  <section class="card"><div class="row"><h3>Training Load COROS</h3><span class="pill">ratio ${v3Num(state.coros.loadRatio)?.toFixed(2)??'–'}</span></div>${loads.length>1?sparkline(loads.map(x=>+x.ratio||0)):'<p class="muted small">Dati insufficienti.</p>'}<div class="grid2"><div class="metric"><small>Breve</small><b>${state.coros.shortLoad??'–'}</b></div><div class="metric"><small>Lungo</small><b>${state.coros.longLoad??'–'}</b></div></div></section>
  <section class="card"><div class="row"><div><h3>Turni</h3><p class="muted tiny" style="margin:0">Google Calendar + eventuali inserimenti manuali</p></div><span class="pill">${all.length}</span></div>${all.length?all.slice(0,30).map(s=>`<div class="history-item"><div class="row"><div><b>${fmtDate(s.date,{weekday:'short',day:'numeric',month:'short'})}</b><div class="muted tiny">${esc(s.title)} · ${esc(s.source||'manuale')}</div></div><span class="pill ${s.load>=3?'warn':''}">carico ${s.load}/4</span></div></div>`).join(''):'<p class="muted small">Nessun turno sincronizzato.</p>'}</section>
  <section class="card"><h3>Aggiungi eccezione manuale</h3><div class="form-grid"><label>Data<input id="shiftDate" type="date" value="${v3Today()}"></label><label>Carico 1–4<select id="shiftLoad"><option value="1">1 · lieve</option><option value="2">2 · medio</option><option value="3">3 · notte/reperibilità</option><option value="4">4 · 24h/combinato</option></select></label></div><label style="margin-top:10px">Descrizione<input id="shiftTitle" placeholder="es. notte reparto"></label><button class="btn secondary" style="margin-top:12px" onclick="addShift()">Salva eccezione</button></section></div>`;
};

sleepPage=function(){
  const d=v3Today(),h=v3HealthDay(d),sleep=v3Series('sleep',30),hrv=v3Series('hrv',30),rhr=v3Series('rhr',30),avg7=v3Median(v3Series('sleep',7).map(x=>x.value));
  const detail=h.sleepDetail||{},deep=detail.deepMinutes!=null?v3Hours(detail.deepMinutes):null,rem=detail.remMinutes!=null?v3Hours(detail.remMinutes):null;
  setHeader('Sonno','notte principale, nap e recupero');
  app.innerHTML=`<div class="stack"><button class="btn ghost smallbtn" onclick="backMore()">‹ Altro</button>
  <section class="grid2">${v3Metric('Notte principale',h.mainSleep!=null?h.mainSleep.toFixed(2)+' h':'–',h.sleepSource)}${v3Metric('Pisolini',h.nap!=null?h.nap.toFixed(2)+' h':'–',h.nap!=null?(h.sleepSource||''):'')}${v3Metric('HRV sonno',h.hrv!=null?Math.round(h.hrv*10)/10+' ms':'–',h.hrvSource)}${v3Metric('FC riposo',h.rhr!=null?Math.round(h.rhr)+' bpm':'–',h.rhrSource)}</section>
  <section class="card"><div class="row"><h3>Ultima notte</h3><span class="pill">${h.sleepSource||'–'}</span></div><div class="grid3" style="margin-top:10px"><div class="metric"><small>Media 7g</small><b>${avg7!=null?avg7.toFixed(1)+' h':'–'}</b></div><div class="metric"><small>Profondo</small><b>${deep!=null?deep.toFixed(1)+' h':'–'}</b></div><div class="metric"><small>REM</small><b>${rem!=null?rem.toFixed(1)+' h':'–'}</b></div></div><p class="muted small">Il sonno principale è separato dai pisolini. Se Apple Health non ha una notte valida, SmartCoach usa COROS come fallback invece di inventare o sommare dati incompatibili.</p></section>
  <section class="card"><h3>Sonno · 30 giorni</h3>${sleep.length>1?sparkline(sleep.map(x=>x.value)):'<p class="muted small">Servono più notti.</p>'}</section>
  <section class="card"><h3>HRV · 30 giorni</h3>${hrv.length>1?sparkline(hrv.map(x=>x.value)):'<p class="muted small">Servono più campioni.</p>'}</section>
  <section class="card"><h3>FC riposo · 30 giorni</h3>${rhr.length>1?sparkline(rhr.map(x=>x.value)):'<p class="muted small">Servono più giorni.</p>'}</section>
  <button class="btn secondary" onclick="syncHealthV3({silent:false,rebuild:true}).then(()=>sleepPage())">Ricalcola dati Health</button></div>`;
};

coachBrief=function(){
  const end=v3Today(),start=dateKey(addDays(TODAY(),-13)),hist=unifiedActivities().filter(a=>a.date>=start&&a.date<=end),strength=hist.filter(a=>a.kind==='strength').length,runs=hist.filter(a=>a.kind==='run'),km=v3Sum(runs.map(a=>a.distanceKm||0)),h=v3HealthDay(end),rec=recommendation(end),lastBody=state.bodyLogs.at(-1)||{};
  return ['SMARTCOACH V3 REPORT',`Periodo: ${start} → ${end}`,`Peso: ${lastBody.weight??state.profile.weightKg} kg`,`Sessioni: ${hist.length}; forza: ${strength}; corsa: ${km.toFixed(1)} km`,`Readiness: ${scoreReadiness(end)}/100; consiglio: ${rec.session.title} (${rec.adjust})`,`Sonno principale: ${h.mainSleep??'–'} h; HRV: ${h.hrv??'–'} ms; RHR: ${h.rhr??'–'} bpm; passi: ${h.steps??'–'}`,`COROS: recovery ${state.coros.recovery?.value??state.coros.recoveryValue??'–'}%; VO2max ${state.coros.vo2max??'–'}; soglia ${state.coros.thresholdPace??'–'}; load ${state.coros.shortLoad??'–'}/${state.coros.longLoad??'–'}`,`Ultime attività: ${hist.slice(0,8).map(a=>a.date+' '+a.name).join(' | ')||'nessuna'}`].join('\n');
};


renderCardio=function(s,date,rec){
  const mins=Math.round((s.mins||35)*(rec.cardioFactor||1)),zones=state.coros.hrZones?.zones||[],z2=zones.find(x=>/resistenza aerobica/i.test(x.name||'')),thr=state.coros.hrZones?.thresholdHr;
  const target=s.quality?'Qualità controllata':(z2?z2.range+' bpm':'Z2 COROS');
  app.innerHTML=`<div class="stack v3stack">
    <section class="card hero"><div class="row start"><div><span class="pill good">Target COROS</span><h2 style="margin-top:10px">${esc(s.title)}</h2><p class="muted small">${esc(s.focus)}</p></div><div class="right"><div class="big">${esc(target)}</div>${thr?`<div class="tiny muted">Soglia FC ${thr} bpm</div>`:''}</div></div>
    <div class="notice goodbox" style="margin-top:14px">${s.quality?'<strong>Qualità controllata:</strong> riscaldamento facile, blocchi brillanti e recuperi; le intensità restano subordinate alle zone COROS.':`Mantieni la seduta soprattutto in <strong>Resistenza aerobica COROS ${esc(z2?.range||'')}</strong>. Il talk test è solo un controllo secondario, non sostituisce la zona.`}</div></section>
    <section class="card"><label>Modalità<select id="cardioMode"><option value="run" ${s.quality||state.settings.cardioDefault==='run'?'selected':''}>Corsa</option><option value="bike" ${!s.quality&&state.settings.cardioDefault==='bike'?'selected':''}>Cyclette</option><option value="course" ${s.quality?'disabled':''}>Corso endurance</option><option value="walk" ${s.quality?'disabled':''}>Camminata veloce</option></select></label>
    <div class="form-grid three" style="margin-top:10px"><label>Minuti<input id="cardioMinutes" type="number" value="${mins}"></label><label>Km<input id="cardioKm" type="number" step="0.1"></label><label>FC media<input id="cardioHr" type="number" placeholder="${z2?z2.range:''}"></label><label>RPE<input id="cardioRpe" type="number" step="0.5" value="${s.quality?6:3}" min="1" max="10"></label><label>W medi<input id="cardioWatts" type="number" placeholder="se disponibili"></label><label>Target rispettato<select id="cardioZ2"><option value="yes">Sì</option><option value="mostly">Quasi tutto</option><option value="no">No</option></select></label></div>
    <label style="margin-top:10px">Note<textarea id="cardioNote" placeholder="Sensazioni, percorso, resistenza cyclette…"></textarea></label><button class="btn" style="margin-top:12px" onclick="saveCardio('${s.id}','${date}')">Salva cardio</button></section>
  </div>`;
};
