'use strict';
function v3FmtMins(mins){if(mins==null)return '–';const m=Math.round(mins);return m>=60?Math.floor(m/60)+'h '+String(m%60).padStart(2,'0')+'m':m+' min'}
function v3ActivityMeta(a){const bits=[];if(a.distanceKm!=null)bits.push(a.distanceKm.toFixed(2)+' km');if(a.minutes!=null)bits.push(v3FmtMins(a.minutes));if(a.avgHr!=null)bits.push('FC '+Math.round(a.avgHr));if(a.trainingLoad!=null)bits.push('Load '+a.trainingLoad);return bits.join(' · ')}
function v3ActivityLine(a){return `<div class="history-item"><div class="row start"><div class="grow"><b>${esc(a.name)}</b><div class="muted tiny">${fmtDate(a.date,{day:'numeric',month:'short'})} · ${esc(a.source||'')}</div></div><span class="pill">${esc(v3ActivityMeta(a)||a.kind)}</span></div></div>`}
function v3Metric(label,value,source,onclick=''){return `<button class="metric metric-btn v3metric" ${onclick?`onclick="${onclick}"`:''}><small>${esc(label)}</small><b>${value}</b>${source?`<em>${esc(source)}</em>`:''}</button>`}
function v3ReasonRows(parts){if(!parts.length)return '<p class="muted small">Mancano ancora dati fisiologici sufficienti.</p>';return parts.slice(0,5).map(x=>`<div class="reason-row"><div><b>${esc(x.label)}</b><small>${esc(x.note||'')} · ${esc(x.source||'')}</small></div><span>${Math.round(x.value)}</span></div>`).join('')}

todayView=function(date=state.selectedDate||v3Today()){
  state.selectedDate=date;save();setTab('today');
  const rec=recommendation(date),rd=v3Readiness(date),h=rd.health,acts=historyOn(date),band=readinessBand(rec.score);
  setHeader(date===v3Today()?'Oggi':fmtDate(date,{weekday:'long',day:'numeric',month:'long'}),'');
  const shift=rd.shift?`<span class="pill warn">${esc(rd.shift.title)}</span>`:'',nap=h.nap&&h.nap>.15?` · +${h.nap.toFixed(1)} h nap`:'';
  const ratio=v3Num(state.coros.loadRatio),short=v3Num(state.coros.shortLoad),long=v3Num(state.coros.longLoad);
  app.innerHTML=`<div class="stack v3stack">
  <section class="card hero v3hero"><div class="row start"><div class="grow"><div class="pills"><span class="pill ${band}">${readinessLabel(rec.score)}</span>${shift}</div><h2 style="margin-top:12px">${esc(rec.session.title)}</h2><p class="muted small">${esc(rec.reason)} · ${esc(rec.session.focus||'')}</p></div><div class="score-ring" style="--score:${rec.score}"><b>${rec.score}</b><small>READY</small></div></div><div class="actions"><button class="btn" onclick="startRecommended('${date}')">${rec.session.type==='recovery'?'Apri':'Inizia'}</button><button class="btn secondary" onclick="openCheckin('${date}')">Come mi sento</button></div></section>
  <section class="grid2 v3health">${v3Metric('Sonno principale',h.mainSleep!=null?h.mainSleep.toFixed(2)+' h'+nap:'–',h.sleepSource,`healthTrendPage('sleep')`)}${v3Metric('HRV sonno',h.hrv!=null?Math.round(h.hrv*10)/10+' ms':'–',h.hrvSource,`healthTrendPage('hrv')`)}${v3Metric('FC riposo',h.rhr!=null?Math.round(h.rhr)+' bpm':'–',h.rhrSource,`healthTrendPage('rhr')`)}${v3Metric('Passi',h.steps!=null?Math.round(h.steps).toLocaleString('it-IT'):'–',h.stepsSource,`healthTrendPage('steps')`)}</section>
  <section class="card"><div class="row"><div><h3>Perché oggi</h3><p class="muted tiny" style="margin:0">Il punteggio cambia solo quando cambiano i dati sottostanti.</p></div><span class="pill">${rec.adjust}</span></div><div style="margin-top:10px">${v3ReasonRows(rd.parts)}</div></section>
  <section class="card"><div class="row"><h3>Carico COROS</h3><span class="pill">${state.coros.synced||state.coros.syncedAt?.slice(0,10)||'–'}</span></div><div class="grid3" style="margin-top:10px"><div class="metric"><small>Breve</small><b>${short??'–'}</b></div><div class="metric"><small>Lungo</small><b>${long??'–'}</b></div><div class="metric"><small>Ratio</small><b>${ratio!=null?ratio.toFixed(2):'–'}</b></div></div></section>
  ${acts.length?`<section class="card"><div class="row"><h3>Registrato oggi</h3><span class="pill good">${acts.length}</span></div>${acts.map(v3ActivityLine).join('')}</section>`:''}
  <section class="card soft"><div class="row"><div><h3>Ultime attività</h3><p class="muted tiny" style="margin:0">COROS + SmartCoach</p></div><button class="swap" onclick="trendView()">Vedi trend</button></div>${unifiedActivities().slice(0,3).map(v3ActivityLine).join('')||'<p class="muted small">Nessuna attività sincronizzata.</p>'}</section></div>`;
};

weekView=function(){
  setTab('week');setHeader('Settimana','piano adattivo + attività reali');
  const {days,plan}=v3PlanWeek(state.selectedDate||v3Today()),today=v3Today();
  const rows=days.map(d=>{const p=plan[d],acts=p.actual||[],actual=acts.length?acts.map(a=>a.name).join(' + '):null,s=p.session,main=actual||s?.short||'Recupero',sub=[];
    if(actual)sub.push('registrato · '+[...new Set(acts.map(a=>a.source))].join('/'));else if(s)sub.push('proposto');if(p.shift)sub.push(p.shift.title);
    return `<button class="day ${d===today?'today':''} ${acts.length?'done':''}" onclick="todayView('${d}')"><div><div class="dow">${parseDate(d).toLocaleDateString('it-IT',{weekday:'short'})}</div><div class="date">${parseDate(d).getDate()}</div></div><div><b>${esc(main)}</b><div class="muted tiny">${sub.map(x=>p.shift&&x===p.shift.title?`<span class="shift">${esc(x)}</span>`:esc(x)).join(' · ')}</div></div><i class="status-dot"></i></button>`}).join('');
  app.innerHTML=`<div class="stack"><section class="card"><div class="notice goodbox">Il piano non è legato ai giorni fissi: attività registrate, recupero e turni spostano automaticamente ciò che resta da fare.</div><div class="week" style="margin-top:12px">${rows}</div></section></div>`;
};

trainingHub=function(){
  setTab('train');setHeader('Training','scegli o segui il piano');const d=v3Today(),rec=recommendation(d),z=state.coros.hrZones||{},run=unifiedActivities().find(a=>a.kind==='run');
  const adaptive=s=>{const raw=typeof s.mins==='number'?s.mins:(s.type==='cardio'?35:50),av=rec.availableMinutes||raw,f=s.type==='cardio'?rec.cardioFactor:(rec.setDelta<=-2?.6:rec.setDelta<0?.8:1);return Math.max(15,Math.round(Math.min(raw,av)*f))};
  const zones=(z.zones||[]).map(x=>`<div class="zone-row"><span>${esc(x.name)}</span><b>${esc(x.range)} bpm</b></div>`).join('');
  app.innerHTML=`<div class="stack v3stack"><section class="card hero"><div class="row"><div><span class="pill good">Consigliato oggi</span><h2 style="margin-top:10px">${esc(rec.session.title)}</h2><p class="muted small">${esc(rec.reason)}</p></div><div class="big">${adaptive(rec.session)}<small class="muted tiny"> min</small></div></div><button class="btn" style="margin-top:12px" onclick="startRecommended('${d}')">Apri allenamento</button></section>
  <section class="card"><div class="segment"><button class="${state.place==='CASA'?'active':''}" onclick="setPlace('CASA')">Casa</button><button class="${state.place==='PALESTRA'?'active':''}" onclick="setPlace('PALESTRA')">Palestra</button></div></section>
  <section class="card"><div class="row"><div><h3>Corsa / cardio</h3><p class="muted tiny" style="margin:0">Zone ufficiali COROS · soglia ${z.thresholdHr??'–'} bpm</p></div><span class="pill">${state.coros.thresholdPace||state.coros.fitness?.thresholdPace||'–'}</span></div><div class="grid2" style="margin-top:12px"><button class="menu" onclick="openSession('z2short','${d}')"><b>Z2 base</b><span>${adaptive(CARDIO.z2short)} min · ${(z.zones||[])[1]?.range||'–'} bpm</span></button><button class="menu" onclick="openSession('z2long','${d}')"><b>Z2 endurance</b><span>${adaptive(CARDIO.z2long)} min</span></button></div>${zones?`<div class="zones-compact">${zones}</div>`:''}${run?`<p class="muted tiny">Ultima corsa: ${esc(v3ActivityMeta(run))}</p>`:''}</section>
  <section class="card"><h3>Forza</h3><div class="menu-grid" style="margin-top:10px">${Object.values(STRENGTH).map(s=>`<button class="menu" onclick="openSession('${s.id}','${d}')"><b>${esc(s.short)}</b><span>${adaptive(s)} min · ${state.place==='CASA'?'casa':'palestra'}</span></button>`).join('')}</div></section></div>`;
};
setPlace=function(p){state.place=p;save();trainingHub()};

function v3RangeDays(){return +state.ui.trendRange||28}
function setTrendRange(n){state.ui.trendRange=n;save();trendView()}
function v3Within(a,days){const start=dateKey(addDays(TODAY(),-(days-1))),end=v3Today();return a.date>=start&&a.date<=end}
function v3WeeklyRunKm(days){const start=addDays(TODAY(),-(days-1)),ws=v3WeekStart(start),weeks=[];for(let d=new Date(ws);d<=TODAY();d=addDays(d,7)){const a=dateKey(d),b=dateKey(addDays(d,6)),km=v3Sum(unifiedActivities().filter(x=>x.kind==='run'&&x.date>=a&&x.date<=b).map(x=>x.distanceKm||0));weeks.push({date:a,value:Math.round(km*100)/100})}return weeks}
function v3LoadSeries(days){const start=dateKey(addDays(TODAY(),-(days-1)));return (state.coros.loadHistory||[]).filter(x=>x.date>=start).map(x=>({date:x.date,value:+x.ratio||0}))}
trendView=function(){
  setTab('trend');setHeader('Trend','dati reali, non baseline statiche');const days=v3RangeDays(),acts=unifiedActivities().filter(a=>v3Within(a,days)),runs=acts.filter(a=>a.kind==='run');
  const km=v3Sum(runs.map(a=>a.distanceKm||0)),active=v3Sum(acts.map(a=>a.minutes||0)),steps=v3Series('steps',days),sleep=v3Series('sleep',days),hrv=v3Series('hrv',days),rhr=v3Series('rhr',days),load=v3LoadSeries(days),runWeeks=v3WeeklyRunKm(days);
  const stepAvg=steps.length?Math.round(v3Sum(steps.map(x=>x.value))/steps.length):null,fitness=state.coros.fitness||state.coros,pred=state.coros.racePredictions||fitness.racePredictions||{};
  const chart=(title,rows,unit='')=>`<section class="card"><div class="row"><h3>${esc(title)}</h3><span class="pill">${rows.length} gg</span></div>${rows.length>1?sparkline(rows.map(x=>+x.value)):'<p class="muted small">Servono più dati sincronizzati.</p>'}${rows.length?`<div class="row tiny muted"><span>${fmtDate(rows[0].date)}</span><span>${Math.round(rows.at(-1).value*100)/100} ${esc(unit)}</span></div>`:''}</section>`;
  app.innerHTML=`<div class="stack v3stack"><section class="card"><div class="segment"><button class="${days===7?'active':''}" onclick="setTrendRange(7)">7g</button><button class="${days===28?'active':''}" onclick="setTrendRange(28)">28g</button><button class="${days===90?'active':''}" onclick="setTrendRange(90)">90g</button></div></section>
  <section class="grid2"><div class="metric"><small>Sessioni · ${days}g</small><b>${acts.length}</b></div><div class="metric"><small>Corsa · ${days}g</small><b>${km.toFixed(1)} km</b></div><div class="metric"><small>Tempo attivo</small><b>${Math.round(active)} min</b></div><div class="metric"><small>Passi medi/g</small><b>${stepAvg!=null?stepAvg.toLocaleString('it-IT'):'–'}</b></div></section>
  <section class="card"><div class="row"><h3>Running Fitness · COROS</h3><span class="pill good">live</span></div><div class="grid2" style="margin-top:10px"><div class="metric"><small>Running Level</small><b>${fitness.runningLevel??'–'}</b></div><div class="metric"><small>VO₂max</small><b>${fitness.vo2max??'–'}</b></div><div class="metric"><small>5 km</small><b>${pred.k5||'–'}</b></div><div class="metric"><small>10 km</small><b>${pred.k10||'–'}</b></div></div></section>
  ${chart('Km corsa · per settimana',runWeeks,'km')}${chart('Passi · giornalieri',steps,'')}${chart('Sonno principale',sleep,'h')}${chart('HRV sonno',hrv,'ms')}${chart('FC riposo',rhr,'bpm')}${chart('Load ratio COROS',load,'')}
  <section class="card"><div class="row"><h3>Storico unificato</h3><span class="pill">${unifiedActivities().length}</span></div>${unifiedActivities().slice(0,40).map(v3ActivityLine).join('')||'<p class="muted">Nessuna attività sincronizzata.</p>'}</section></div>`;
};

healthTrendPage=function(kind){
  const meta={sleep:['Sonno principale','h'],hrv:['HRV sonno','ms'],rhr:['FC a riposo','bpm'],steps:['Passi','']},m=meta[kind]||meta.hrv,rows=v3Series(kind,90);
  setHeader(m[0],'ultimi 90 giorni');setTab('today');app.innerHTML=`<div class="stack"><button class="btn ghost smallbtn" onclick="todayView()">‹ Oggi</button><section class="card"><div class="row"><h2>${m[0]}</h2><span class="pill">${rows.length} gg</span></div>${rows.length>1?sparkline(rows.map(x=>x.value)):'<p class="muted small">Dati insufficienti.</p>'}${rows.slice(-30).reverse().map(x=>`<div class="history-item row"><span>${fmtDate(x.date,{day:'numeric',month:'short'})}</span><b>${Math.round(x.value*100)/100} ${m[1]}</b></div>`).join('')}</section>${kind==='sleep'?'<section class="card"><p class="muted small">Il valore principale è la notte; i pisolini restano separati e non gonfiano il sonno notturno.</p></section>':''}</div>`;
};
openCheckin=function(date=state.selectedDate||v3Today()){
  const r=state.readiness?.[date]||{},h=v3HealthDay(date);setHeader('Come mi sento',fmtDate(date,{weekday:'long',day:'numeric',month:'long'}));
  app.innerHTML=`<div class="stack"><section class="card"><div class="notice goodbox">Sonno, HRV, FC riposo e COROS Recovery arrivano automaticamente. Qui inserisci solo ciò che il sensore non può sapere.</div><div class="form-grid" style="margin-top:14px"><label>Energia<select id="ciEnergy">${opts5(r.energy||3)}</select></label><label>Dolori muscolari<select id="ciSore">${opts5(r.soreness||2)}</select></label><label>Stress<select id="ciStress">${opts5(r.stress||3)}</select></label><label>Tempo disponibile<select id="ciTime"><option value="20" ${+r.availableMinutes===20?'selected':''}>20 min</option><option value="35" ${+r.availableMinutes===35?'selected':''}>35 min</option><option value="50" ${!r.availableMinutes||+r.availableMinutes===50?'selected':''}>50 min</option><option value="60" ${+r.availableMinutes===60?'selected':''}>60+ min</option></select></label></div><div class="grid3" style="margin-top:12px"><div class="metric"><small>Sonno auto</small><b>${h.mainSleep!=null?h.mainSleep.toFixed(1)+' h':'–'}</b></div><div class="metric"><small>HRV auto</small><b>${h.hrv!=null?Math.round(h.hrv)+' ms':'–'}</b></div><div class="metric"><small>RHR auto</small><b>${h.rhr!=null?Math.round(h.rhr):'–'}</b></div></div><button class="btn" style="margin-top:14px" onclick="saveCheckinV3('${date}')">Salva</button></section></div>`;
};
function saveCheckinV3(date){state.readiness[date]={...(state.readiness[date]||{}),energy:+val('ciEnergy'),soreness:+val('ciSore'),stress:+val('ciStress'),availableMinutes:+val('ciTime')||50};save();toast('Check-in salvato');todayView(date)}
